/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Token } from "./Token";
export type { TokenVote } from "./TokenVote";
export type { VTS } from "./VTS";
export type { VotingSystem } from "./VotingSystem";
