/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { EventFragment, FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

import type { OnEvent, TypedEvent, TypedEventFilter, TypedListener } from "../common";

export interface VotingSystemInterface extends utils.Interface {
  functions: {
    "addHackathon(string,string,uint256,uint256,address)": FunctionFragment;
    "addProject(string,string,string,string,address)": FunctionFragment;
    "balances(address)": FunctionFragment;
    "calculateTopVotedProject()": FunctionFragment;
    "currentHackathon()": FunctionFragment;
    "delegatePerson(address,uint256)": FunctionFragment;
    "getBalance(address)": FunctionFragment;
    "getRightForVote(address,uint256)": FunctionFragment;
    "getWinnerProject()": FunctionFragment;
    "governor()": FunctionFragment;
    "hackathons(uint256)": FunctionFragment;
    "printHackathon(uint256)": FunctionFragment;
    "printProject(uint256,uint256)": FunctionFragment;
    "token()": FunctionFragment;
    "vote(uint256)": FunctionFragment;
    "voters(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addHackathon"
      | "addProject"
      | "balances"
      | "calculateTopVotedProject"
      | "currentHackathon"
      | "delegatePerson"
      | "getBalance"
      | "getRightForVote"
      | "getWinnerProject"
      | "governor"
      | "hackathons"
      | "printHackathon"
      | "printProject"
      | "token"
      | "vote"
      | "voters",
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addHackathon",
    values: [string, string, BigNumberish, BigNumberish, string],
  ): string;
  encodeFunctionData(functionFragment: "addProject", values: [string, string, string, string, string]): string;
  encodeFunctionData(functionFragment: "balances", values: [string]): string;
  encodeFunctionData(functionFragment: "calculateTopVotedProject", values?: undefined): string;
  encodeFunctionData(functionFragment: "currentHackathon", values?: undefined): string;
  encodeFunctionData(functionFragment: "delegatePerson", values: [string, BigNumberish]): string;
  encodeFunctionData(functionFragment: "getBalance", values: [string]): string;
  encodeFunctionData(functionFragment: "getRightForVote", values: [string, BigNumberish]): string;
  encodeFunctionData(functionFragment: "getWinnerProject", values?: undefined): string;
  encodeFunctionData(functionFragment: "governor", values?: undefined): string;
  encodeFunctionData(functionFragment: "hackathons", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "printHackathon", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "printProject", values: [BigNumberish, BigNumberish]): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(functionFragment: "vote", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "voters", values: [string]): string;

  decodeFunctionResult(functionFragment: "addHackathon", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addProject", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "calculateTopVotedProject", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "currentHackathon", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "delegatePerson", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRightForVote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getWinnerProject", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "governor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hackathons", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "printHackathon", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "printProject", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "voters", data: BytesLike): Result;

  events: {
    "DelegatePerson(address,uint256)": EventFragment;
    "HackathonAdded(string,string,uint256,uint256,address)": EventFragment;
    "ProjectAdded(string,string,string,string,address,uint256)": EventFragment;
    "RightToVoteGiven(address,uint256)": EventFragment;
    "Voted(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DelegatePerson"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "HackathonAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProjectAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RightToVoteGiven"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Voted"): EventFragment;
}

export interface DelegatePersonEventObject {
  _user: string;
  _amount: BigNumber;
}
export type DelegatePersonEvent = TypedEvent<[string, BigNumber], DelegatePersonEventObject>;

export type DelegatePersonEventFilter = TypedEventFilter<DelegatePersonEvent>;

export interface HackathonAddedEventObject {
  _name: string;
  _description: string;
  _endDate: BigNumber;
  _votingEnd: BigNumber;
  _owner: string;
}
export type HackathonAddedEvent = TypedEvent<[string, string, BigNumber, BigNumber, string], HackathonAddedEventObject>;

export type HackathonAddedEventFilter = TypedEventFilter<HackathonAddedEvent>;

export interface ProjectAddedEventObject {
  _name: string;
  _description: string;
  _contractAddress: string;
  _frontEndURL: string;
  _owner: string;
  votes: BigNumber;
}
export type ProjectAddedEvent = TypedEvent<
  [string, string, string, string, string, BigNumber],
  ProjectAddedEventObject
>;

export type ProjectAddedEventFilter = TypedEventFilter<ProjectAddedEvent>;

export interface RightToVoteGivenEventObject {
  _to: string;
  _amount: BigNumber;
}
export type RightToVoteGivenEvent = TypedEvent<[string, BigNumber], RightToVoteGivenEventObject>;

export type RightToVoteGivenEventFilter = TypedEventFilter<RightToVoteGivenEvent>;

export interface VotedEventObject {
  _user: string;
  _teamNumber: BigNumber;
}
export type VotedEvent = TypedEvent<[string, BigNumber], VotedEventObject>;

export type VotedEventFilter = TypedEventFilter<VotedEvent>;

export interface VotingSystem extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VotingSystemInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addHackathon(
      _name: string,
      _description: string,
      _endDate: BigNumberish,
      _votingEnd: BigNumberish,
      _ownerAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    addProject(
      _name: string,
      _description: string,
      _contractAddress: string,
      _frontEndURL: string,
      _owner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    balances(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    calculateTopVotedProject(overrides?: CallOverrides): Promise<[BigNumber]>;

    currentHackathon(overrides?: CallOverrides): Promise<[BigNumber]>;

    delegatePerson(
      _user: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    getBalance(_address: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    getRightForVote(
      _voterAddress: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    getWinnerProject(overrides?: CallOverrides): Promise<[string, string, string]>;

    governor(overrides?: CallOverrides): Promise<[string]>;

    hackathons(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [string, string, BigNumber, BigNumber, string] & {
        name: string;
        description: string;
        endDate: BigNumber;
        votingEndDate: BigNumber;
        owner: string;
      }
    >;

    printHackathon(index: BigNumberish, overrides?: CallOverrides): Promise<[void]>;

    printProject(hIndex: BigNumberish, pIndex: BigNumberish, overrides?: CallOverrides): Promise<[void]>;

    token(overrides?: CallOverrides): Promise<[string]>;

    vote(
      projectNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    voters(
      arg0: string,
      overrides?: CallOverrides,
    ): Promise<
      [boolean, BigNumber, string] & {
        voted: boolean;
        vote: BigNumber;
        delegate: string;
      }
    >;
  };

  addHackathon(
    _name: string,
    _description: string,
    _endDate: BigNumberish,
    _votingEnd: BigNumberish,
    _ownerAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  addProject(
    _name: string,
    _description: string,
    _contractAddress: string,
    _frontEndURL: string,
    _owner: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  balances(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  calculateTopVotedProject(overrides?: CallOverrides): Promise<BigNumber>;

  currentHackathon(overrides?: CallOverrides): Promise<BigNumber>;

  delegatePerson(
    _user: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  getBalance(_address: string, overrides?: CallOverrides): Promise<BigNumber>;

  getRightForVote(
    _voterAddress: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  getWinnerProject(overrides?: CallOverrides): Promise<[string, string, string]>;

  governor(overrides?: CallOverrides): Promise<string>;

  hackathons(
    arg0: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<
    [string, string, BigNumber, BigNumber, string] & {
      name: string;
      description: string;
      endDate: BigNumber;
      votingEndDate: BigNumber;
      owner: string;
    }
  >;

  printHackathon(index: BigNumberish, overrides?: CallOverrides): Promise<void>;

  printProject(hIndex: BigNumberish, pIndex: BigNumberish, overrides?: CallOverrides): Promise<void>;

  token(overrides?: CallOverrides): Promise<string>;

  vote(
    projectNumber: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  voters(
    arg0: string,
    overrides?: CallOverrides,
  ): Promise<
    [boolean, BigNumber, string] & {
      voted: boolean;
      vote: BigNumber;
      delegate: string;
    }
  >;

  callStatic: {
    addHackathon(
      _name: string,
      _description: string,
      _endDate: BigNumberish,
      _votingEnd: BigNumberish,
      _ownerAddress: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    addProject(
      _name: string,
      _description: string,
      _contractAddress: string,
      _frontEndURL: string,
      _owner: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    balances(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    calculateTopVotedProject(overrides?: CallOverrides): Promise<BigNumber>;

    currentHackathon(overrides?: CallOverrides): Promise<BigNumber>;

    delegatePerson(_user: string, _amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    getBalance(_address: string, overrides?: CallOverrides): Promise<BigNumber>;

    getRightForVote(_voterAddress: string, _amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    getWinnerProject(overrides?: CallOverrides): Promise<[string, string, string]>;

    governor(overrides?: CallOverrides): Promise<string>;

    hackathons(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [string, string, BigNumber, BigNumber, string] & {
        name: string;
        description: string;
        endDate: BigNumber;
        votingEndDate: BigNumber;
        owner: string;
      }
    >;

    printHackathon(index: BigNumberish, overrides?: CallOverrides): Promise<void>;

    printProject(hIndex: BigNumberish, pIndex: BigNumberish, overrides?: CallOverrides): Promise<void>;

    token(overrides?: CallOverrides): Promise<string>;

    vote(projectNumber: BigNumberish, overrides?: CallOverrides): Promise<void>;

    voters(
      arg0: string,
      overrides?: CallOverrides,
    ): Promise<
      [boolean, BigNumber, string] & {
        voted: boolean;
        vote: BigNumber;
        delegate: string;
      }
    >;
  };

  filters: {
    "DelegatePerson(address,uint256)"(_user?: null, _amount?: null): DelegatePersonEventFilter;
    DelegatePerson(_user?: null, _amount?: null): DelegatePersonEventFilter;

    "HackathonAdded(string,string,uint256,uint256,address)"(
      _name?: null,
      _description?: null,
      _endDate?: null,
      _votingEnd?: null,
      _owner?: null,
    ): HackathonAddedEventFilter;
    HackathonAdded(
      _name?: null,
      _description?: null,
      _endDate?: null,
      _votingEnd?: null,
      _owner?: null,
    ): HackathonAddedEventFilter;

    "ProjectAdded(string,string,string,string,address,uint256)"(
      _name?: null,
      _description?: null,
      _contractAddress?: null,
      _frontEndURL?: null,
      _owner?: null,
      votes?: null,
    ): ProjectAddedEventFilter;
    ProjectAdded(
      _name?: null,
      _description?: null,
      _contractAddress?: null,
      _frontEndURL?: null,
      _owner?: null,
      votes?: null,
    ): ProjectAddedEventFilter;

    "RightToVoteGiven(address,uint256)"(_to?: null, _amount?: null): RightToVoteGivenEventFilter;
    RightToVoteGiven(_to?: null, _amount?: null): RightToVoteGivenEventFilter;

    "Voted(address,uint256)"(_user?: null, _teamNumber?: null): VotedEventFilter;
    Voted(_user?: null, _teamNumber?: null): VotedEventFilter;
  };

  estimateGas: {
    addHackathon(
      _name: string,
      _description: string,
      _endDate: BigNumberish,
      _votingEnd: BigNumberish,
      _ownerAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    addProject(
      _name: string,
      _description: string,
      _contractAddress: string,
      _frontEndURL: string,
      _owner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    balances(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    calculateTopVotedProject(overrides?: CallOverrides): Promise<BigNumber>;

    currentHackathon(overrides?: CallOverrides): Promise<BigNumber>;

    delegatePerson(
      _user: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    getBalance(_address: string, overrides?: CallOverrides): Promise<BigNumber>;

    getRightForVote(
      _voterAddress: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    getWinnerProject(overrides?: CallOverrides): Promise<BigNumber>;

    governor(overrides?: CallOverrides): Promise<BigNumber>;

    hackathons(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    printHackathon(index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    printProject(hIndex: BigNumberish, pIndex: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<BigNumber>;

    vote(projectNumber: BigNumberish, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    voters(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addHackathon(
      _name: string,
      _description: string,
      _endDate: BigNumberish,
      _votingEnd: BigNumberish,
      _ownerAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    addProject(
      _name: string,
      _description: string,
      _contractAddress: string,
      _frontEndURL: string,
      _owner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    balances(arg0: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    calculateTopVotedProject(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    currentHackathon(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    delegatePerson(
      _user: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    getBalance(_address: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRightForVote(
      _voterAddress: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    getWinnerProject(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    governor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hackathons(arg0: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    printHackathon(index: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    printProject(hIndex: BigNumberish, pIndex: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    token(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    vote(
      projectNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    voters(arg0: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
