/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Token__factory } from "./Token__factory";
export { TokenVote__factory } from "./TokenVote__factory";
export { VTS__factory } from "./VTS__factory";
export { VotingSystem__factory } from "./VotingSystem__factory";
